### ISSUE TITLE
Cortex-Mixins generates Angular Graph panels which will be deprecated in Grafana 11

### ISSUE THREAD

**Issue by SuperMatt** [cortexproject/cortex-jsonnet#44]
As per the title, the cortex-mixins currently generate the Angular graph panel types which will be deprecated in Grafana 11 later this year. They should be replaced by the React based Timeseries panels.

**Comment by friedrichg** [comment]
yes, we are using a bunch of deprecated stuff. 
The only one I see failing for now is Cortex Service Scaling since Grafana 11.

![Screenshot 2024-05-27 at 10 30 14](https://github.com/cortexproject/cortex-jsonnet/assets/1517449/9a960e7c-4cb4-4bff-9eb3-032fbf0fd1c8)

**Comment by SuperMatt** [comment]
Hi @friedrichg, I've been going through my list of dashboards that need to be migrated and I notice that the Rollout Progress dashboard has a single panel that needs to be migrated. I think we might want to re-open this issue.

![image](https://github.com/cortexproject/cortex-jsonnet/assets/3635576/c320037d-2342-43ba-b3ba-8429b7b718c1)

**Comment by friedrichg** [comment]
@SuperMatt thanks for the info. Let me double check it
